DEFAULT_DATE_FORMAT = "%d/%m/%y"
PRODUCT_ID_COLUMN_NAME = 'product_id'
CATEGORY_ID_COLUMN_NAME = 'category_id'
REVENUE_COLUMN_NAME = 'revenue'
QUANTITY_COLUMN_NAME = 'quantity'
DATE_COLUMN_NAME = 'date'